[main]
# http port for monitor and reload
httpPort=8992

# max number of CPUs to use
maxCpus = 8

# interval for get diff of proxy-state
# NOTE: this value MUST match the monitor parameters
#       of noah to generate alert correctly
monitorInterval = 20


# for bfe_access_pb
[PbAccessLogConf]
LogFile = /home/work/bfe/log/pb_access3.log 
Modules = mod_kafka
